### ISSUE TITLE
DB생성 sql 작성

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project3#1]
초기 EER-Diagram에 따라 db 테이블 생성 sql 작성 ver1
mysql 사용

**Comment by YeChanSong** [comment]
확인했습니다. :)

**Comment by luxlunae15** [comment]
특정 table에 NOT NULL 제거

**Comment by luxlunae15** [comment]
판매자와 관리자 테이블 PHONE field 추가

**Comment by luxlunae15** [comment]
위치 정보를 location 테이블저장에서 위도와 경도로 수정

**Comment by luxlunae15** [comment]
매장이 추가 되면 trigger를 통해 store_user 테이블에 판매자 ID와 매장 ID INSERT

**Comment by luxlunae15** [comment]
리뷰 테이블에 좋아요 추가

**Comment by thsgustlr0318** [comment]
확인했습니다.
