### ISSUE TITLE
상품 조회/리뷰/평점 기능

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project3#40]
매장을 통해 상품을 보고, 리뷰와 평점 기록

**Comment by luxlunae15** [comment]
리뷰를 남길 때 평점을 같이 기록할 수 있도록 하였고, 리뷰가 없더라도 편점만 입력도 가능하게 구현

**Comment by luxlunae15** [comment]
매장의 기존 평점과 새로 들어온 평점을 평균내어 매장에 새로운 평점 등록

**Comment by thsgustlr0318** [comment]
확인했습니다.
