### ISSUE TITLE
매장을 통한 상품들 관리

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project3#43]
상품들을 잘 관리할 수 있도록 매장을 나누어 판매자 별 매장을 통해 관리하는 기능

**Comment by luxlunae15** [comment]
카테고리를 통해 매장을 나누고, 판매자들이 매장을 관리하여 매장을 통해 상품들을 관리함

**Comment by YeChanSong** [comment]
확인했습니다.
